# coding: utf-8

"""
    HLS - Tests

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2017-03-02T13:53:08Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import hls_tests
from hls_tests.rest import ApiException
from hls_tests.models.empty import Empty


class TestEmpty(unittest.TestCase):
    """ Empty unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmpty(self):
        """
        Test Empty
        """
        model = hls_tests.models.empty.Empty()


if __name__ == '__main__':
    unittest.main()
