# coding: utf-8

"""
    HLS - Tests

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2017-03-02T13:53:08Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import hls_tests
from hls_tests.rest import ApiException
from hls_tests.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = hls_tests.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_test_delete(self):
        """
        Test case for test_delete

        
        """
        pass

    def test_test_get(self):
        """
        Test case for test_get

        
        """
        pass

    def test_test_options(self):
        """
        Test case for test_options

        
        """
        pass

    def test_test_put(self):
        """
        Test case for test_put

        
        """
        pass

    def test_tests_get(self):
        """
        Test case for tests_get

        
        """
        pass

    def test_tests_options(self):
        """
        Test case for tests_options

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
